version: '3.1'

services:
    db:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: nautidb
            MYSQL_USER: nautiuser
            MYSQL_PASSWORD: nautipass